---
title: "Lab 1"
author: "Ahmed Hassan"
date: "10/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r initialization, echo=FALSE, include=FALSE}
suppressPackageStartupMessages(require(ggplot2))
suppressPackageStartupMessages(require(dplyr))
suppressPackageStartupMessages(require(readxl))
suppressPackageStartupMessages(require(tidyverse))
suppressPackageStartupMessages(require(nycflights13))
library(ggplot2)
library(readxl)
library(dplyr)
library(tidyverse)


defense <- read_excel('cyclonesFootball2019.xlsx', sheet='Defensive')
offense <- read_excel('cyclonesFootball2019.xlsx', sheet='Offensive')
biography <- read_excel('cyclonesFootball2019.xlsx', sheet='Biography')

str(defense)
```

PART 1
1-3

```{r}
defense$Name <- as.factor(unlist(defense$Name))
defense$Opponent_Opponent <- as.factor(unlist(defense$Opponent_Opponent))
offense$Name <- as.factor(unlist(offense$Name))
offense$Opponent_Opponent <- as.factor(unlist(offense$Opponent_Opponent))

defClean <- defense %>%
  mutate(Tackles_Solo = as.numeric(Tackles_Solo), Tackles_ASST = as.numeric(Tackles_ASST), Tackles_TFL = as.numeric(Tackles_TFL),Tackles_Sack = as.numeric(Tackles_Sack), Turnover_FF = as.numeric(Turnover_FF),Turnover_FR = as.numeric(Turnover_FR), Turnover_INT = as.numeric(Turnover_INT), Pass_QBH = as.numeric(Pass_QBH), Pass_PB =as.numeric(Pass_PB))
#str(defClean)
print(defClean)

offClean <- offense %>%
  mutate(Rushing_ATT = as.numeric(Rushing_ATT),  Rushing_YDS=as.numeric(Rushing_YDS), Rushing_TD = as.numeric(Rushing_TD), Receiving_REC = as.numeric(Receiving_REC), Receiving_YDS = as.numeric(Receiving_YDS), Receiving_TD = as.numeric(Receiving_TD),`Passing_CMP-ATT` = as.numeric(`Passing_CMP-ATT`), Passing_YDS = as.numeric(Passing_YDS), Passing_TD = as.numeric(Passing_TD), Passing_INT = as.numeric(Passing_INT))
#str(offClean)
print(offClean)

bioClean <- biography %>%
  mutate(Weight = as.numeric(Weight)) %>%
  separate(Height, c("Feet", "Inches"), sep='-') %>%
  mutate(Feet = as.numeric(Feet), Inches = as.numeric(Inches)) %>%
  mutate(Feet = as.numeric(Feet*12)) %>%
  mutate(Feet = as.numeric(Feet*2.54), Inches =as.numeric(Inches*2.54)) %>%
  mutate(Height = rowSums(.[3:4])) %>%
  select(-c(Feet,Inches))
  print(bioClean)

```
PART 2 
1)
```{r}
print(defClean)
defClean<- defClean %>% 
  pivot_longer(Tackles_Solo:Pass_PB, names_to = "stat", values_to = "score" ) 


```
2)
```{r}
table(defClean$stat, defClean$score > 0)
```
```
By viewing the score that are greater than Zero,  we can see that the Turnover Statistics are the rarest of the all the statistics
```
3)Did ISU have better defense against Iowa or Notre Dame? Answer this question by creating a scatterplot with x- and y-axes being the number of solo tackles (of each player). A large number of solo tackles is an indicator of good defense.
```{r}
p3 <- defense %>%  
  filter(Opponent_Opponent == "Iowa" | Opponent_Opponent == "Notre Dame" ) %>% 
  pivot_longer(Tackles_Solo:Pass_PB, names_to = "stat", values_to = "score" ) %>% 
  filter(stat == "Tackles_Solo") 

p3_Iowa<- p3 %>% 
  filter(Opponent_Opponent =="Iowa")

p3_Notre <- p3 %>% 
  filter(Opponent_Opponent== "Notre Dame")

p3_full <- merge(p3_Iowa, p3_Notre)

ggplot(p3_Iowa, aes(x= Name, y = score, color = Opponent_Opponent)) + geom_point() + theme(axis.text.x=element_text(angle=90,margin = margin(1, unit = "cm"),vjust =1)) + labs( title= "ISU vs Iowa", y="Score", x = "Player Name")
ggplot(p3_Notre, aes(x= Name, y = score, color = Opponent_Opponent)) + geom_point() + theme(axis.text.x=element_text(angle=90,margin = margin(1, unit = "cm"),vjust =1))+ labs( title= "ISU vs Notre Dame", y="Score", x = "Player Name")

```
```
Based on the two graphs generated above, We can say that Isu head better defense against Notre Dame, having the most players acheiving multiple takcles within one game, compared to ISU

```
Part 3. 

1.
```{r}

distinctDefense <- defense[1] %>% distinct()
editBio <- biography[c(1,6)]
distinctDefense<- inner_join(distinctDefense, editBio, by= "Name")
distinctDefense %>% 
  summarise(Name, Hometown)

distinctOffense <- offense[1] %>% distinct()
distinctOffense<- inner_join(distinctOffense, editBio, by= "Name")
distinctOffense %>% 
  summarise(Name, Hometown)

```
```
The Summary above gives each of the players hometowns
```
2. 
```{r}
offenseDF <- offense %>%  pivot_longer(Rushing_ATT:Passing_INT, names_to = 'Stat', values_to = 'offensiveScore')
offenseDF <- na.omit(offenseDF)
offenseDF <- offenseDF[c(1,4)]


purdyDF<- offenseDF %>% filter(Name == 'Purdy, Brock')


offenseDF %>% 
  group_by(Name) %>%
  filter(offensiveScore != "0") %>% 
   arrange(desc(offensiveScore)) %>% 
   summarise(Name, offensiveScore)

purdyDF %>% 
  filter(offensiveScore != "0" ) %>% 
  arrange(desc(offensiveScore)) %>% 
  summarise(Name, offensiveScore)

```
```
As we can see from the 2 summaries shown above, one for the Offensive scores of all the iS players, and theother for Brock Purdy's personal Offensive Score, we cna conclude that as a quarterback, Brock's performance in terms of this Offensice scores are higher than that of the rest of the teams members. Brock's summary also shows that he acheived the maximum offensive scores per game compared to the rest of his team.
```
3.
```{r}
defense2 <- read_excel('cyclonesFootball2019.xlsx', sheet='Defensive')
str(defense2)
offense2 <- read_excel('cyclonesFootball2019.xlsx', sheet='Offensive')
bio2 <- read_excel('cyclonesFootball2019.xlsx', sheet='Biography')

defClean2 <- defense2 %>%
  mutate(Tackles_Solo = as.numeric(Tackles_Solo), Tackles_ASST = as.numeric(Tackles_ASST), Tackles_TFL = as.numeric(Tackles_TFL),Tackles_Sack = as.numeric(Tackles_Sack), Turnover_FF = as.numeric(Turnover_FF),Turnover_FR = as.numeric(Turnover_FR), Turnover_INT = as.numeric(Turnover_INT), Pass_QBH = as.numeric(Pass_QBH), Pass_PB =as.numeric(Pass_PB))
defClean2$Name <- as.factor(unlist(defClean2$Name))
defClean2$Opponent_Opponent <- as.factor(unlist(defClean2$Opponent_Opponent))


offClean2 <- offense2 %>%
  mutate(Rushing_ATT = as.numeric(Rushing_ATT),  Rushing_YDS=as.numeric(Rushing_YDS), Rushing_TD = as.numeric(Rushing_TD), Receiving_REC = as.numeric(Receiving_REC), Receiving_YDS = as.numeric(Receiving_YDS), Receiving_TD = as.numeric(Receiving_TD),`Passing_CMP-ATT` = as.numeric(`Passing_CMP-ATT`), Passing_YDS = as.numeric(Passing_YDS), Passing_TD = as.numeric(Passing_TD), Passing_INT = as.numeric(Passing_INT))
offClean2$Name <- as.factor(unlist(offClean2$Name))
#str(offClean)


bioClean2 <- bio2 %>%
  mutate(Weight = as.numeric(Weight)) %>%
  separate(Height, c("Feet", "Inches"), sep='-') %>%
  mutate(Feet = as.numeric(Feet), Inches = as.numeric(Inches)) %>%
  mutate(Feet = as.numeric(Feet*12)) %>%
  mutate(Feet = as.numeric(Feet*2.54), Inches =as.numeric(Inches*2.54)) %>%
  mutate(Height = rowSums(.[3:4])) %>%
  select(-c(Feet,Inches))
```


